---------------------------------------
Begin Slurm Prolog: Apr-09-2024 22:56:58
Job ID:    5609559
User ID:   cchen847
Account:   gts-rs275
Job name:  nerf2_test
Partition: gpu-a100
QOS:       inferno
---------------------------------------
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scipy==1.10.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (1.10.0)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from scipy==1.10.0) (1.26.4)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mne==1.6.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (1.6.1)
Requirement already satisfied: pooch>=1.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (1.8.1)
Requirement already satisfied: packaging in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (21.3)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (0.4)
Requirement already satisfied: scipy>=1.7.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (1.10.0)
Requirement already satisfied: tqdm in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (4.66.2)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (2.11.3)
Requirement already satisfied: numpy>=1.21.2 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (1.26.4)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (5.1.1)
Requirement already satisfied: matplotlib>=3.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (3.8.4)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (1.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (0.11.0)
Requirement already satisfied: pillow>=8 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (9.0.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (1.3.2)
Requirement already satisfied: pyparsing>=2.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (3.0.4)
Requirement already satisfied: importlib-resources>=3.2.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (6.4.0)
Requirement already satisfied: zipp>=3.1.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.5.0->mne==1.6.1) (3.7.0)
Requirement already satisfied: requests>=2.19.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne==1.6.1) (2.31.0)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne==1.6.1) (4.2.0)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->mne==1.6.1) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (3.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (2021.10.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (1.26.18)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne==1.6.1) (2.0.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mne_bids in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (0.13)
Requirement already satisfied: mne>=1.4 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.6.1)
Requirement already satisfied: scipy>=1.6.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.10.0)
Requirement already satisfied: numpy>=1.20.2 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.26.4)
Requirement already satisfied: packaging in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (21.3)
Requirement already satisfied: tqdm in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (4.66.2)
Requirement already satisfied: matplotlib>=3.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (3.8.4)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (5.1.1)
Requirement already satisfied: pooch>=1.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (1.8.1)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (2.11.3)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (0.4)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (6.4.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.3.2)
Requirement already satisfied: pillow>=8 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (9.0.1)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (3.0.4)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.2.1)
Requirement already satisfied: zipp>=3.1.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.5.0->mne>=1.4->mne_bids) (3.7.0)
Requirement already satisfied: requests>=2.19.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne>=1.4->mne_bids) (2.31.0)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne>=1.4->mne_bids) (4.2.0)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (1.26.18)
Requirement already satisfied: charset-normalizer<4,>=2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (2.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne>=1.4->mne_bids) (2.0.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyriemann in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (0.5)
Requirement already satisfied: numpy!=1.24.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann) (1.26.4)
Requirement already satisfied: joblib in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann) (1.4.0)
Requirement already satisfied: scikit-learn in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann) (1.4.2)
Requirement already satisfied: scipy in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann) (1.10.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn->pyriemann) (2.2.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: scipy>=1.6.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from scikit-learn) (1.10.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: joblib>=1.2.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from scikit-learn) (1.4.0)
Requirement already satisfied: numpy>=1.19.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from scikit-learn) (1.26.4)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: moabb in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (1.0.0)
Requirement already satisfied: pandas<2.0.0,>=1.5.2 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.5.3)
Requirement already satisfied: scipy<2.0.0,>=1.9.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.10.0)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from moabb) (6.0)
Requirement already satisfied: tqdm<5.0.0,>=4.64.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (4.66.2)
Requirement already satisfied: memory-profiler<0.62.0,>=0.61.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (0.61.0)
Requirement already satisfied: pooch<2.0.0,>=1.6.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.8.1)
Requirement already satisfied: edflib-python<2.0.0,>=1.0.6 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.0.8)
Requirement already satisfied: numpy<2.0,>=1.22 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.26.4)
Requirement already satisfied: h5py<=3.8.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from moabb) (3.6.0)
Requirement already satisfied: seaborn<0.13.0,>=0.12.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (0.12.2)
Requirement already satisfied: scikit-learn<2.0.0,>=1.2.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.4.2)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (2.31.0)
Requirement already satisfied: pytest<8.0.0,>=7.4.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (7.4.4)
Requirement already satisfied: urllib3<2.0.0,>=1.26.15 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.26.18)
Requirement already satisfied: pyriemann<0.6,>=0.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (0.5)
Requirement already satisfied: coverage<8.0.0,>=7.0.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (7.4.4)
Requirement already satisfied: mne-bids<0.14,>=0.13 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (0.13)
Requirement already satisfied: mne<2.0,>=1.4 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.6.1)
Requirement already satisfied: matplotlib<4.0.0,>=3.6.2 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (3.8.4)
Requirement already satisfied: importlib-resources>=3.2.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (6.4.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (1.3.2)
Requirement already satisfied: packaging>=20.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (21.3)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (0.11.0)
Requirement already satisfied: pillow>=8 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (9.0.1)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (1.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (3.0.4)
Requirement already satisfied: zipp>=3.1.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib<4.0.0,>=3.6.2->moabb) (3.7.0)
Requirement already satisfied: psutil in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from memory-profiler<0.62.0,>=0.61.0->moabb) (5.8.0)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne<2.0,>=1.4->moabb) (2.11.3)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne<2.0,>=1.4->moabb) (0.4)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne<2.0,>=1.4->moabb) (5.1.1)
Requirement already satisfied: pytz>=2020.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pandas<2.0.0,>=1.5.2->moabb) (2021.3)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch<2.0.0,>=1.6.0->moabb) (4.2.0)
Requirement already satisfied: joblib in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann<0.6,>=0.5->moabb) (1.4.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.0.0)
Requirement already satisfied: tomli>=1.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.2.2)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.2.0)
Requirement already satisfied: iniconfig in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.1.1)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.6.2->moabb) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests<3.0.0,>=2.28.1->moabb) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests<3.0.0,>=2.28.1->moabb) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests<3.0.0,>=2.28.1->moabb) (2021.10.8)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.2.0->moabb) (2.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne<2.0,>=1.4->moabb) (2.0.1)
Downloading file 'S001/S001R06.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R06.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R10.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R10.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R14.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R14.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Processing raw data for subject 1
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? Traceback (most recent call last):
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1175, in _safe_input
    return input(msg)
EOFError: EOF when reading a line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_hands_feet_MI.py", line 202, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions, path=args.download_path)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 223, in load_data
    _do_path_update(path, update_path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 153, in _do_path_update
    answer = _safe_input(msg, alt="pass update_path=True")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1179, in _safe_input
    raise RuntimeError(
RuntimeError: Could not use input() to get a response to:
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? 
You can pass update_path=True to avoid this error.
Downloading file 'S001/S001R04.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R04.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R08.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R08.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R12.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R12.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Processing raw data for subject 1
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? Traceback (most recent call last):
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1175, in _safe_input
    return input(msg)
EOFError: EOF when reading a line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_left_right_MI.py", line 202, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions, path=args.download_path)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 223, in load_data
    _do_path_update(path, update_path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 153, in _do_path_update
    answer = _safe_input(msg, alt="pass update_path=True")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1179, in _safe_input
    raise RuntimeError(
RuntimeError: Could not use input() to get a response to:
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? 
You can pass update_path=True to avoid this error.
Downloading file 'S001/S001R05.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R05.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R09.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R09.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R13.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R13.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Processing raw data for subject 1
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? Traceback (most recent call last):
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1175, in _safe_input
    return input(msg)
EOFError: EOF when reading a line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_hands_feet_ME.py", line 202, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions, path=args.download_path)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 223, in load_data
    _do_path_update(path, update_path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 153, in _do_path_update
    answer = _safe_input(msg, alt="pass update_path=True")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1179, in _safe_input
    raise RuntimeError(
RuntimeError: Could not use input() to get a response to:
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? 
You can pass update_path=True to avoid this error.
Downloading file 'S001/S001R03.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R03.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R07.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R07.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Downloading file 'S001/S001R11.edf' from 'https://physionet.org/files/eegmmidb/1.0.0/S001/S001R11.edf' to '/storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data/MNE-eegbci-data/files/eegmmidb/1.0.0'.
Processing raw data for subject 1
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? Traceback (most recent call last):
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1175, in _safe_input
    return input(msg)
EOFError: EOF when reading a line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_left_right_ME.py", line 202, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions, path=args.download_path)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 223, in load_data
    _do_path_update(path, update_path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 153, in _do_path_update
    answer = _safe_input(msg, alt="pass update_path=True")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/utils/check.py", line 1179, in _safe_input
    raise RuntimeError(
RuntimeError: Could not use input() to get a response to:
Do you want to set the path:
    /storage/home/hcoda1/3/cchen847/p-rs275-0/da_eeg/mDA/mne-data
as the default EEGBCI dataset path in the mne-python config [y]/n? 
You can pass update_path=True to avoid this error.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Shin2017A.py", line 208, in <module>
    data = dataset1.get_data(subjects=subjects, cache_config={'path': args.download_path})
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 132, in _get_single_subject_data
    fname, fname_mrk = self.data_path(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 181, in data_path
    path = _get_path(path, key, "BBCI EEG-fNIRS")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Shin2017B.py", line 208, in <module>
    data = dataset1.get_data(subjects=subjects, cache_config={'path': args.download_path})
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 132, in _get_single_subject_data
    fname, fname_mrk = self.data_path(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 181, in data_path
    path = _get_path(path, key, "BBCI EEG-fNIRS")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_BNCI.py", line 208, in <module>
    data = dataset1.get_data(subjects=subjects, cache_config={'path': args.download_path})
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 738, in _get_single_subject_data
    sessions = load_data(subject=subject, dataset=self.code, verbose=False)
  File "<decorator-gen-435>", line 10, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 111, in load_data
    return dataset_list[dataset](
  File "<decorator-gen-443>", line 10, in _load_data_004_2015
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 411, in _load_data_004_2015
    filename = data_path(url, path, force_update, update_path)[0]
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 20, in data_path
    return [dl.data_dl(url, "BNCI", path, force_update, verbose)]
  File "<decorator-gen-434>", line 12, in data_dl
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/download.py", line 136, in data_dl
    path = Path(get_dataset_path(sign, path))
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/download.py", line 56, in get_dataset_path
    return _get_path(path, key, sign)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Schirrmeister.py", line 210, in <module>
    data = dataset1.get_data(subjects=subjects)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 132, in _get_single_subject_data
    fname, fname_mrk = self.data_path(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 181, in data_path
    path = _get_path(path, key, "BBCI EEG-fNIRS")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
---------------------------------------
Begin Slurm Epilog: Apr-09-2024 22:58:47
Job ID:        5609559
Array Job ID:  _4294967294
User ID:       cchen847
Account:       gts-rs275
Job name:      nerf2_test
Resources:     cpu=8,gres/gpu:a100=1,mem=10G,node=1
Rsrc Used:     cput=00:14:32,vmem=175748K,walltime=00:01:49,mem=175696K,energy_used=0
Partition:     gpu-a100
QOS:           inferno
Nodes:         atl1-1-02-018-29-0
---------------------------------------
