---------------------------------------
Begin Slurm Prolog: Apr-09-2024 22:40:10
Job ID:    5609523
User ID:   cchen847
Account:   gts-rs275
Job name:  nerf2_test
Partition: gpu-a100
QOS:       inferno
---------------------------------------
Defaulting to user installation because normal site-packages is not writeable
Collecting scipy==1.10.0
  Downloading scipy-1.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scipy==1.10.0) (1.21.5)
Installing collected packages: scipy
Successfully installed scipy-1.10.0
Defaulting to user installation because normal site-packages is not writeable
Collecting mne==1.6.1
  Downloading mne-1.6.1-py3-none-any.whl (8.3 MB)
Requirement already satisfied: tqdm in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (4.64.0)
Requirement already satisfied: scipy>=1.7.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (1.10.0)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (2.11.3)
Requirement already satisfied: packaging in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (21.3)
Collecting lazy-loader>=0.3
  Downloading lazy_loader-0.4-py3-none-any.whl (12 kB)
Collecting pooch>=1.5
  Downloading pooch-1.8.1-py3-none-any.whl (62 kB)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (5.1.1)
Requirement already satisfied: matplotlib>=3.5.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (3.5.1)
Requirement already satisfied: numpy>=1.21.2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (1.21.5)
Requirement already satisfied: pillow>=6.2.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (3.0.4)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (4.25.0)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (1.3.2)
Collecting platformdirs>=2.5.0
  Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
Requirement already satisfied: requests>=2.19.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pooch>=1.5->mne==1.6.1) (2.27.1)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->mne==1.6.1) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (2021.10.8)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne==1.6.1) (2.0.1)
Installing collected packages: platformdirs, pooch, lazy-loader, mne
  WARNING: The script mne is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed lazy-loader-0.4 mne-1.6.1 platformdirs-4.2.0 pooch-1.8.1
Defaulting to user installation because normal site-packages is not writeable
Collecting mne_bids
  Downloading mne_bids-0.14-py2.py3-none-any.whl (1.2 MB)
Requirement already satisfied: scipy>=1.6.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.10.0)
Requirement already satisfied: numpy>=1.20.2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne_bids) (1.21.5)
Requirement already satisfied: mne>=1.4 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.6.1)
Requirement already satisfied: packaging in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (21.3)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (2.11.3)
Requirement already satisfied: tqdm in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (4.64.0)
Requirement already satisfied: matplotlib>=3.5.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (3.5.1)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (0.4)
Requirement already satisfied: pooch>=1.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (1.8.1)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (5.1.1)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (3.0.4)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (0.11.0)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne>=1.4->mne_bids) (4.2.0)
Requirement already satisfied: requests>=2.19.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pooch>=1.5->mne>=1.4->mne_bids) (2.27.1)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (2.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne>=1.4->mne_bids) (2.0.1)
Installing collected packages: mne-bids
  WARNING: The script mne_bids is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed mne-bids-0.14
Defaulting to user installation because normal site-packages is not writeable
Collecting braindecode
  Downloading braindecode-0.8.1-py3-none-any.whl (165 kB)
Collecting skorch
  Downloading skorch-0.15.0-py3-none-any.whl (239 kB)
Requirement already satisfied: mne in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from braindecode) (1.6.1)
Requirement already satisfied: joblib in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from braindecode) (1.1.0)
Requirement already satisfied: matplotlib in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from braindecode) (3.5.1)
Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Requirement already satisfied: scipy in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from braindecode) (1.10.0)
Collecting einops
  Downloading einops-0.7.0-py3-none-any.whl (44 kB)
Requirement already satisfied: pandas in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from braindecode) (1.4.2)
Collecting torch
  Downloading torch-2.2.2-cp39-cp39-manylinux1_x86_64.whl (755.5 MB)
Requirement already satisfied: numpy in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from braindecode) (1.21.5)
Requirement already satisfied: h5py in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from braindecode) (3.6.0)
Collecting docstring-inheritance
  Downloading docstring_inheritance-2.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (4.25.0)
Requirement already satisfied: packaging>=20.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib->braindecode) (9.0.1)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->braindecode) (1.16.0)
Requirement already satisfied: tqdm in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne->braindecode) (4.64.0)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne->braindecode) (5.1.1)
Requirement already satisfied: pooch>=1.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne->braindecode) (1.8.1)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne->braindecode) (2.11.3)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne->braindecode) (0.4)
Requirement already satisfied: requests>=2.19.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pooch>=1.5->mne->braindecode) (2.27.1)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne->braindecode) (4.2.0)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne->braindecode) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne->braindecode) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne->braindecode) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne->braindecode) (2021.10.8)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne->braindecode) (2.0.1)
Requirement already satisfied: pytz>=2020.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pandas->braindecode) (2021.3)
Requirement already satisfied: tabulate>=0.7.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from skorch->braindecode) (0.8.9)
Requirement already satisfied: scikit-learn>=0.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from skorch->braindecode) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn>=0.22.0->skorch->braindecode) (2.2.0)
Collecting nvidia-cublas-cu12==12.1.3.1
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Requirement already satisfied: sympy in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from torch->braindecode) (1.10.1)
Collecting nvidia-cuda-cupti-cu12==12.1.105
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-curand-cu12==10.3.2.106
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-nccl-cu12==2.19.3
  Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
Requirement already satisfied: filelock in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from torch->braindecode) (3.6.0)
Collecting typing-extensions>=4.8.0
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Requirement already satisfied: fsspec in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from torch->braindecode) (2022.2.0)
Collecting nvidia-nvtx-cu12==12.1.105
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting triton==2.2.0
  Downloading triton-2.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Requirement already satisfied: networkx in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from torch->braindecode) (2.7.1)
Collecting nvidia-cuda-runtime-cu12==12.1.105
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-nvjitlink-cu12
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
Requirement already satisfied: mpmath>=0.19 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from sympy->torch->braindecode) (1.2.1)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-cusparse-cu12, nvidia-cublas-cu12, typing-extensions, triton, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusolver-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, torchinfo, torch, skorch, einops, docstring-inheritance, braindecode
ERROR: Could not install packages due to an OSError: [Errno 122] Disk quota exceeded

Defaulting to user installation because normal site-packages is not writeable
Collecting pyriemann
  Downloading pyriemann-0.5.tar.gz (119 kB)
Requirement already satisfied: numpy!=1.24.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann) (1.21.5)
Requirement already satisfied: scipy in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann) (1.10.0)
Requirement already satisfied: scikit-learn in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann) (1.0.2)
Requirement already satisfied: joblib in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn->pyriemann) (2.2.0)
Building wheels for collected packages: pyriemann
  Building wheel for pyriemann (setup.py): started
  Building wheel for pyriemann (setup.py): finished with status 'done'
  WARNING: Building wheel for pyriemann failed: [Errno 122] Disk quota exceeded
  Running setup.py clean for pyriemann
Failed to build pyriemann
Installing collected packages: pyriemann
    Running setup.py install for pyriemann: started
    Running setup.py install for pyriemann: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch/5609523/pip-install-p43tt670/pyriemann_43ef4f531e97402888fa8b7c9f265807/setup.py'"'"'; __file__='"'"'/scratch/5609523/pip-install-p43tt670/pyriemann_43ef4f531e97402888fa8b7c9f265807/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /scratch/5609523/pip-record-xfiiozig/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /storage/home/hcoda1/3/cchen847/.local/include/python3.9/pyriemann
         cwd: /scratch/5609523/pip-install-p43tt670/pyriemann_43ef4f531e97402888fa8b7c9f265807/
    Complete output (51 lines):
    running install
    /usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/pyriemann
    copying pyriemann/__init__.py -> build/lib/pyriemann
    copying pyriemann/_version.py -> build/lib/pyriemann
    copying pyriemann/channelselection.py -> build/lib/pyriemann
    copying pyriemann/classification.py -> build/lib/pyriemann
    copying pyriemann/clustering.py -> build/lib/pyriemann
    copying pyriemann/embedding.py -> build/lib/pyriemann
    copying pyriemann/estimation.py -> build/lib/pyriemann
    copying pyriemann/preprocessing.py -> build/lib/pyriemann
    copying pyriemann/regression.py -> build/lib/pyriemann
    copying pyriemann/spatialfilters.py -> build/lib/pyriemann
    copying pyriemann/stats.py -> build/lib/pyriemann
    copying pyriemann/tangentspace.py -> build/lib/pyriemann
    creating build/lib/pyriemann/datasets
    copying pyriemann/datasets/__init__.py -> build/lib/pyriemann/datasets
    copying pyriemann/datasets/sampling.py -> build/lib/pyriemann/datasets
    copying pyriemann/datasets/simulated.py -> build/lib/pyriemann/datasets
    creating build/lib/pyriemann/transfer
    copying pyriemann/transfer/__init__.py -> build/lib/pyriemann/transfer
    copying pyriemann/transfer/_estimators.py -> build/lib/pyriemann/transfer
    copying pyriemann/transfer/_rotate.py -> build/lib/pyriemann/transfer
    copying pyriemann/transfer/_tools.py -> build/lib/pyriemann/transfer
    creating build/lib/pyriemann/utils
    copying pyriemann/utils/__init__.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/ajd.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/base.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/covariance.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/distance.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/docs.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/geodesic.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/kernel.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/mean.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/median.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/tangentspace.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/test.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/utils.py -> build/lib/pyriemann/utils
    copying pyriemann/utils/viz.py -> build/lib/pyriemann/utils
    running install_lib
    creating /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann
    copying build/lib/pyriemann/__init__.py -> /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann
    copying build/lib/pyriemann/_version.py -> /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann
    copying build/lib/pyriemann/channelselection.py -> /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann
    copying build/lib/pyriemann/classification.py -> /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann
    error: [Errno 122] Disk quota exceeded
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch/5609523/pip-install-p43tt670/pyriemann_43ef4f531e97402888fa8b7c9f265807/setup.py'"'"'; __file__='"'"'/scratch/5609523/pip-install-p43tt670/pyriemann_43ef4f531e97402888fa8b7c9f265807/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /scratch/5609523/pip-record-xfiiozig/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /storage/home/hcoda1/3/cchen847/.local/include/python3.9/pyriemann Check the logs for full command output.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: numpy>=1.14.6 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (1.21.5)
Requirement already satisfied: joblib>=0.11 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from scikit-learn) (1.10.0)
Defaulting to user installation because normal site-packages is not writeable
Collecting moabb
  Downloading moabb-1.0.0-py3-none-any.whl (563 kB)
Requirement already satisfied: mne<2.0,>=1.4 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.6.1)
Collecting seaborn<0.13.0,>=0.12.1
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting pandas<2.0.0,>=1.5.2
  Downloading pandas-1.5.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Collecting coverage<8.0.0,>=7.0.1
  Downloading coverage-7.4.4-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (233 kB)
Collecting pyriemann<0.6,>=0.5
  Using cached pyriemann-0.5-py2.py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 140, in __bool__
    return any(self)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
    super().__init__(
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 61, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages/pip/_internal/distributions/wheel.py", line 26, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/local/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-dy2uo6w3 because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_hands_feet_MI.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-n6wbos3_ because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_left_right_MI.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-8t70iedr because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_hands_feet_ME.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-oxt2u8yh because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_left_right_ME.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-q6l2n7n9 because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Shin2017A.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-mp4f58dt because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Shin2017B.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-ftj1imdv because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_BNCI.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
Matplotlib created a temporary config/cache directory at /scratch/5609523/matplotlib-ckj2e2ke because the default path (/storage/home/hcoda1/3/cchen847/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Schirrmeister.py", line 24, in <module>
    import pyriemann
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py", line 3, in <module>
    from . import tangentspace
ImportError: cannot import name 'tangentspace' from partially initialized module 'pyriemann' (most likely due to a circular import) (/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/pyriemann/__init__.py)
---------------------------------------
Begin Slurm Epilog: Apr-09-2024 22:43:54
Job ID:        5609523
Array Job ID:  _4294967294
User ID:       cchen847
Account:       gts-rs275
Job name:      nerf2_test
Resources:     cpu=8,gres/gpu:a100=1,mem=10G,node=1
Rsrc Used:     cput=00:29:52,vmem=7515016K,walltime=00:03:44,mem=105332K,energy_used=0
Partition:     gpu-a100
QOS:           inferno
Nodes:         atl1-1-02-018-29-0
---------------------------------------
